### PR TITLE
Add resize-from-nearest-corner behavior and improve precision/smoothness

### PR DESCRIPTION
**Pull request by jli**
I haven't ever done OS X or Swift programming, so I'm sure things might be slightly wonky, feedback welcome.

I didn't add a config option for the nearest-corner resizing. It would be easy to add a conditional to `resizeWindow` and do the old behavior (same code as `corner==4`). But I don't really know how to add config options :).

### CODE REVIEW

**Comment by jli** [comment]
Good point on the enum, fixed.

I've been using this over the past few days and have been liking it. Some remaining issues:
- Slight bug: if you resize upwards when the window is already up against the menu bar, the window height still increases by growing _downwards_.
- Somewhat related: I often want to the resizing to stop once I hit the edge of the screen (like default OS X resizing), but this currently lets you keep resizing. (Actually, it seems like resizing is bounded on the top, right, and bottom screen edges but not the left edge, bizarrely.) I think fixing this issue will also fix the previous one.

I think I would also prefer it if the move function stopped me from moving windows off the screen edge, since I'm often wanting to push windows against the edges/corners, but that currently requires slow precision to do. Curious what you think about that?
(I do occasionally find it useful to move a window off the edge of the screen, but you can still use the usual titlebar dragging to get that.)

**Comment by rxhanson** [comment]
Excellent points. I think I might like to fix all three of them before rolling this into an official release (depending on how much time I can put into it). In addition to the screen edge moving, it would be nice to have at least a little bit of sticky edge logic implemented, like how it is in macOS with the title bar. Of course, all of this requires a decent amount more complexity since knowing where screen edges are requires you to check the bounds of all displays every time you start a move (or resize) action. Not hard stuff, but definitely can be time consuming to get it all right. I would completely understand if this is as far as you wanted to take it but would definitely point you in the proper directions if you wanted to take it further. I definitely appreciate what you've done so far!

**Comment by jli** [comment]
Ah, I was thinking sticky logic wouldn't be necessary if there was just a hard stop at the current screen edges, but I realize multiple displays (which I don't usually use) makes this more complex.

I'd be happy to give multi-display support a shot if you could point me at the relevant docs or some example code, thanks!

**Comment by jli** [comment]
I implemented resize restrictions as well as move restrictions in this separate PR: #2 
For my single screen usage, I like this a lot. I can now fling the mouse to the corner/edge to quickly move/expand the window without precise positioning or needing to slow down for macOS's sticky positioning to kick in.

Now, multiple displays. I think this logic should be straightforward to implement, and also be pretty intuitive:
- When moving slow, the move/resize action stops at the current screen boundary.
- When moving fast, the action continues onto adjacent displays (until the outermost boundary is reached).
- Speed is tracked with an averaged pixels/second value, which could be configurable.
- The actions are still bounded by the edges of all displays, so in the single-screen case, fast moves will still stop at the edges.
WDYT?

Unfortunately I don't have any of the requisite dongles immediately on hand to test multiple displays...(I _might_ be able to locate one, but not sure.) I saw Rectangle has some multi-screen handling, so I could do my best to implement it "blind".

**Comment by rxhanson** [comment]
Wow, you're taking this and running. I really like the resize and move restrictions. I think a little playing with the values and it'll feel just like macOS title bar drag to me. The corner resizing is great, too. I'm wondering if it is possible to make the window fix its right edge when you resize from one of the left corners since there's a little jumpiness in that edge. From what I've done so far, I think that might not be easily fixable. Also, once you reach the minimum size of a window during a left to right resize, it would be nice to prevent the window from continuing to move to the right. Didn't get a chance to run your sticky edge today but should get to it soon.

**Comment by rxhanson** [comment]
I'm almost ready to pick up where you left off on these. Gonna go ahead and merge them into this ModMove fork and start from there. Thanks for your help! It might take some time to roll this into a release but I'll keep you posted when I do.

**Comment by jli** [comment]
> I'm almost ready to pick up where you left off on these. Gonna go ahead and merge them into this ModMove fork and start from there. Thanks for your help! It might take some time to roll this into a release but I'll keep you posted when I do.

Hey Ryan, just curious if this made it into a Hookshot release? I was just setting up a new computer and it seems like Hookshot's resizing is still from the bottom-right corner only.

Thanks!

**Comment by rxhanson** [comment]
Hey @jli, thanks for following up! In short, the nearest corner did not make it into Hookshot (sorry!). Since there wasn't a way to keep the left side of the window from fluctuating on left corner moves, I ended up not pushing forward with getting this in. Hookshot's code now deviates pretty far from ModMove, which unfortunately would require a decent amount of rewriting what you have here. You might have noticed that the screen edge boundaries logic from your ModMove PR did make it into Hookshot, at least. If I roll in the nearest corners, I'll post back here. 

I can always build and sign a release of this ModMove repo with your changes, too, if desired.

**Comment by jli** [comment]
Thanks for the update! I thought this patch improved the left-edge jumping issue, but maybe there were some edge cases.

>  If I roll in the nearest corners, I'll post back here.

Sweet, thanks. I've just been using Rectangle and my own fork of ModMove in the mean time.

**Pull request merged**
